### ISSUE TITLE
Using Handlebars with Config.IsDevelopment = true causes a panic

### ISSUE THREAD

**Issue by liamdawson** [iris-contrib/template#1]
With the following code:

```
	app := iris.New()
	app.Config.IsDevelopment = true
	app.Config.DisableBanner = true
	app.Config.Gzip = true

	config := handlebars.DefaultConfig()
	config.Layout = "layouts/layout.html"

	app.Get("/users/add", func(ctx *iris.Context) {
		ctx.MustRender("user_add.html", map[string]interface{}{})
	})
```

viewing `/users/add` causes a panic:

```
panic: Helper already registered: url

goroutine 20 [running]:
panic(0xbf4de0, 0xc820208c80)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/aymerick/raymond.RegisterHelper(0xd1b010, 0x3, 0xbbb7c0, 0xc8202b3ac0)
	/home/liamdawson/workspace/go/src/github.com/aymerick/raymond/helper.go:42 +0x335
github.com/aymerick/raymond.RegisterHelpers(0xc8202cabd0)
	/home/liamdawson/workspace/go/src/github.com/aymerick/raymond/helper.go:54 +0xbd
github.com/iris-contrib/template/handlebars.(*Engine).LoadDirectory(0xc8202cacf0, 0xd1f770, 0xb, 0xd11278, 0x5, 0x0, 0x0)
	/home/liamdawson/workspace/go/src/github.com/iris-contrib/template/handlebars/handlebars.go:56 +0x44
github.com/kataras/iris.(*templateEngineWrapper).load(0xc8202cadb0, 0x0, 0x0)
	/home/liamdawson/workspace/go/src/github.com/kataras/iris/template.go:145 +0x146
github.com/kataras/iris.(*templateEngineWrapper).execute(0xc8202cadb0, 0xc820014cd0, 0xd380c0, 0xd, 0xae63a0, 0xc8201cb170, 0x0, 0x0, 0x0, 0x0, ...)
	/home/liamdawson/workspace/go/src/github.com/kataras/iris/template.go:163 +0x1d4
github.com/kataras/iris.(*Context).RenderWithStatus(0xc820014cd0, 0xc8, 0xd380c0, 0xd, 0xae63a0, 0xc8201cb170, 0x0, 0x0, 0x0, 0x0, ...)
	/home/liamdawson/workspace/go/src/github.com/kataras/iris/context.go:476 +0x117
github.com/kataras/iris.(*Context).Render(0xc820014cd0, 0xd380c0, 0xd, 0xae63a0, 0xc8201cb170, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/liamdawson/workspace/go/src/github.com/kataras/iris/context.go:489 +0xcd
github.com/kataras/iris.(*Context).MustRender(0xc820014cd0, 0xd380c0, 0xd, 0xae63a0, 0xc8201cb170, 0x0, 0x0, 0x0)
	/home/liamdawson/workspace/go/src/github.com/kataras/iris/context.go:496 +0x8b
```

Changing `app.Config.IsDevelopment` to `= false` causes the application to work as expected.

**Comment by kataras** [comment]
Hello, Ok I see what's happening will fix soon

**Comment by kataras** [comment]
@liamdawson Thanks for the report, 
upgrade templates `go get -u github.com/iris-contrib/template` .

Could you please verify that is working?

**Comment by liamdawson** [comment]
```
$ go get -u github.com/iris-contrib/template
package github.com/iris-contrib/template: no buildable Go source files in /home/liamdawson/workspace/go/src/github.com/iris-contrib/template
```

**Comment by kataras** [comment]
Sorry, try to get one of the template engines, `go get -u github.com/iris-contrib/template/html`

**Comment by liamdawson** [comment]
No dice. :(

```
panic: Helper already registered: url

goroutine 20 [running]:
panic(0xd283c0, 0xc820210e60)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/aymerick/raymond.RegisterHelper(0xe75440, 0x3, 0xcea840, 0xc8202b5d10)
	/home/liamdawson/workspace/go/src/github.com/aymerick/raymond/helper.go:42 +0x335
github.com/aymerick/raymond.RegisterHelpers(0xc8202a4ab0)
	/home/liamdawson/workspace/go/src/github.com/aymerick/raymond/helper.go:54 +0xbd
github.com/iris-contrib/template/handlebars.(*Engine).LoadDirectory(0xc8202a4bd0, 0xe7a2a0, 0xb, 0xe6ac60, 0x5, 0x0, 0x0)
	/home/liamdawson/workspace/go/src/github.com/iris-contrib/template/handlebars/handlebars.go:65 +0x3e
github.com/kataras/iris.(*templateEngineWrapper).load(0xc8202a4c90, 0x0, 0x0)
	/home/liamdawson/workspace/go/src/github.com/kataras/iris/template.go:145 +0x146
github.com/kataras/iris.(*templateEngineWrapper).execute(0xc8202a4c90, 0xc820014cd0, 0xe94a60, 0xd, 0xbfc040, 0xc8201cc3c0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/liamdawson/workspace/go/src/github.com/kataras/iris/template.go:163 +0x1d4
github.com/kataras/iris.(*Context).RenderWithStatus(0xc820014cd0, 0xc8, 0xe94a60, 0xd, 0xbfc040, 0xc8201cc3c0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/liamdawson/workspace/go/src/github.com/kataras/iris/context.go:537 +0x117
github.com/kataras/iris.(*Context).Render(0xc820014cd0, 0xe94a60, 0xd, 0xbfc040, 0xc8201cc3c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/liamdawson/workspace/go/src/github.com/kataras/iris/context.go:550 +0xcd
github.com/kataras/iris.(*Context).MustRender(0xc820014cd0, 0xe94a60, 0xd, 0xbfc040, 0xc8201cc3c0, 0x0, 0x0, 0x0)
	/home/liamdawson/workspace/go/src/github.com/kataras/iris/context.go:557 +0x8b
```

**Comment by kataras** [comment]
100% my fault, I'm sorry, try again now, it should be fixed!

**Comment by liamdawson** [comment]
That did the trick! :smile:
